# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canoncical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/bin/cmake-gui

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /usr/local/scenix/samples/SDLNV

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /usr/local/scenix/samples/SDLNV

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/cmake-gui -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /usr/local/scenix/samples/SDLNV/CMakeFiles /usr/local/scenix/samples/SDLNV/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /usr/local/scenix/samples/SDLNV/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named SDLNV

# Build rule for target.
SDLNV: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 SDLNV
.PHONY : SDLNV

# fast build rule for target.
SDLNV/fast:
	$(MAKE) -f CMakeFiles/SDLNV.dir/build.make CMakeFiles/SDLNV.dir/build
.PHONY : SDLNV/fast

src/Agent.o: src/Agent.cpp.o
.PHONY : src/Agent.o

# target to build an object file
src/Agent.cpp.o:
	$(MAKE) -f CMakeFiles/SDLNV.dir/build.make CMakeFiles/SDLNV.dir/src/Agent.cpp.o
.PHONY : src/Agent.cpp.o

src/Agent.i: src/Agent.cpp.i
.PHONY : src/Agent.i

# target to preprocess a source file
src/Agent.cpp.i:
	$(MAKE) -f CMakeFiles/SDLNV.dir/build.make CMakeFiles/SDLNV.dir/src/Agent.cpp.i
.PHONY : src/Agent.cpp.i

src/Agent.s: src/Agent.cpp.s
.PHONY : src/Agent.s

# target to generate assembly for a file
src/Agent.cpp.s:
	$(MAKE) -f CMakeFiles/SDLNV.dir/build.make CMakeFiles/SDLNV.dir/src/Agent.cpp.s
.PHONY : src/Agent.cpp.s

src/AgentDynamic.o: src/AgentDynamic.cpp.o
.PHONY : src/AgentDynamic.o

# target to build an object file
src/AgentDynamic.cpp.o:
	$(MAKE) -f CMakeFiles/SDLNV.dir/build.make CMakeFiles/SDLNV.dir/src/AgentDynamic.cpp.o
.PHONY : src/AgentDynamic.cpp.o

src/AgentDynamic.i: src/AgentDynamic.cpp.i
.PHONY : src/AgentDynamic.i

# target to preprocess a source file
src/AgentDynamic.cpp.i:
	$(MAKE) -f CMakeFiles/SDLNV.dir/build.make CMakeFiles/SDLNV.dir/src/AgentDynamic.cpp.i
.PHONY : src/AgentDynamic.cpp.i

src/AgentDynamic.s: src/AgentDynamic.cpp.s
.PHONY : src/AgentDynamic.s

# target to generate assembly for a file
src/AgentDynamic.cpp.s:
	$(MAKE) -f CMakeFiles/SDLNV.dir/build.make CMakeFiles/SDLNV.dir/src/AgentDynamic.cpp.s
.PHONY : src/AgentDynamic.cpp.s

src/CameraSystem.o: src/CameraSystem.cpp.o
.PHONY : src/CameraSystem.o

# target to build an object file
src/CameraSystem.cpp.o:
	$(MAKE) -f CMakeFiles/SDLNV.dir/build.make CMakeFiles/SDLNV.dir/src/CameraSystem.cpp.o
.PHONY : src/CameraSystem.cpp.o

src/CameraSystem.i: src/CameraSystem.cpp.i
.PHONY : src/CameraSystem.i

# target to preprocess a source file
src/CameraSystem.cpp.i:
	$(MAKE) -f CMakeFiles/SDLNV.dir/build.make CMakeFiles/SDLNV.dir/src/CameraSystem.cpp.i
.PHONY : src/CameraSystem.cpp.i

src/CameraSystem.s: src/CameraSystem.cpp.s
.PHONY : src/CameraSystem.s

# target to generate assembly for a file
src/CameraSystem.cpp.s:
	$(MAKE) -f CMakeFiles/SDLNV.dir/build.make CMakeFiles/SDLNV.dir/src/CameraSystem.cpp.s
.PHONY : src/CameraSystem.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/SDLNV.dir/build.make CMakeFiles/SDLNV.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/SDLNV.dir/build.make CMakeFiles/SDLNV.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/SDLNV.dir/build.make CMakeFiles/SDLNV.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

usr/local/scenix/samples/common/src/AIScene.o: usr/local/scenix/samples/common/src/AIScene.cpp.o
.PHONY : usr/local/scenix/samples/common/src/AIScene.o

# target to build an object file
usr/local/scenix/samples/common/src/AIScene.cpp.o:
	$(MAKE) -f CMakeFiles/SDLNV.dir/build.make CMakeFiles/SDLNV.dir/usr/local/scenix/samples/common/src/AIScene.cpp.o
.PHONY : usr/local/scenix/samples/common/src/AIScene.cpp.o

usr/local/scenix/samples/common/src/AIScene.i: usr/local/scenix/samples/common/src/AIScene.cpp.i
.PHONY : usr/local/scenix/samples/common/src/AIScene.i

# target to preprocess a source file
usr/local/scenix/samples/common/src/AIScene.cpp.i:
	$(MAKE) -f CMakeFiles/SDLNV.dir/build.make CMakeFiles/SDLNV.dir/usr/local/scenix/samples/common/src/AIScene.cpp.i
.PHONY : usr/local/scenix/samples/common/src/AIScene.cpp.i

usr/local/scenix/samples/common/src/AIScene.s: usr/local/scenix/samples/common/src/AIScene.cpp.s
.PHONY : usr/local/scenix/samples/common/src/AIScene.s

# target to generate assembly for a file
usr/local/scenix/samples/common/src/AIScene.cpp.s:
	$(MAKE) -f CMakeFiles/SDLNV.dir/build.make CMakeFiles/SDLNV.dir/usr/local/scenix/samples/common/src/AIScene.cpp.s
.PHONY : usr/local/scenix/samples/common/src/AIScene.cpp.s

usr/local/scenix/samples/common/src/MeshGenerator.o: usr/local/scenix/samples/common/src/MeshGenerator.cpp.o
.PHONY : usr/local/scenix/samples/common/src/MeshGenerator.o

# target to build an object file
usr/local/scenix/samples/common/src/MeshGenerator.cpp.o:
	$(MAKE) -f CMakeFiles/SDLNV.dir/build.make CMakeFiles/SDLNV.dir/usr/local/scenix/samples/common/src/MeshGenerator.cpp.o
.PHONY : usr/local/scenix/samples/common/src/MeshGenerator.cpp.o

usr/local/scenix/samples/common/src/MeshGenerator.i: usr/local/scenix/samples/common/src/MeshGenerator.cpp.i
.PHONY : usr/local/scenix/samples/common/src/MeshGenerator.i

# target to preprocess a source file
usr/local/scenix/samples/common/src/MeshGenerator.cpp.i:
	$(MAKE) -f CMakeFiles/SDLNV.dir/build.make CMakeFiles/SDLNV.dir/usr/local/scenix/samples/common/src/MeshGenerator.cpp.i
.PHONY : usr/local/scenix/samples/common/src/MeshGenerator.cpp.i

usr/local/scenix/samples/common/src/MeshGenerator.s: usr/local/scenix/samples/common/src/MeshGenerator.cpp.s
.PHONY : usr/local/scenix/samples/common/src/MeshGenerator.s

# target to generate assembly for a file
usr/local/scenix/samples/common/src/MeshGenerator.cpp.s:
	$(MAKE) -f CMakeFiles/SDLNV.dir/build.make CMakeFiles/SDLNV.dir/usr/local/scenix/samples/common/src/MeshGenerator.cpp.s
.PHONY : usr/local/scenix/samples/common/src/MeshGenerator.cpp.s

usr/local/scenix/samples/common/src/SceneFunctions.o: usr/local/scenix/samples/common/src/SceneFunctions.cpp.o
.PHONY : usr/local/scenix/samples/common/src/SceneFunctions.o

# target to build an object file
usr/local/scenix/samples/common/src/SceneFunctions.cpp.o:
	$(MAKE) -f CMakeFiles/SDLNV.dir/build.make CMakeFiles/SDLNV.dir/usr/local/scenix/samples/common/src/SceneFunctions.cpp.o
.PHONY : usr/local/scenix/samples/common/src/SceneFunctions.cpp.o

usr/local/scenix/samples/common/src/SceneFunctions.i: usr/local/scenix/samples/common/src/SceneFunctions.cpp.i
.PHONY : usr/local/scenix/samples/common/src/SceneFunctions.i

# target to preprocess a source file
usr/local/scenix/samples/common/src/SceneFunctions.cpp.i:
	$(MAKE) -f CMakeFiles/SDLNV.dir/build.make CMakeFiles/SDLNV.dir/usr/local/scenix/samples/common/src/SceneFunctions.cpp.i
.PHONY : usr/local/scenix/samples/common/src/SceneFunctions.cpp.i

usr/local/scenix/samples/common/src/SceneFunctions.s: usr/local/scenix/samples/common/src/SceneFunctions.cpp.s
.PHONY : usr/local/scenix/samples/common/src/SceneFunctions.s

# target to generate assembly for a file
usr/local/scenix/samples/common/src/SceneFunctions.cpp.s:
	$(MAKE) -f CMakeFiles/SDLNV.dir/build.make CMakeFiles/SDLNV.dir/usr/local/scenix/samples/common/src/SceneFunctions.cpp.s
.PHONY : usr/local/scenix/samples/common/src/SceneFunctions.cpp.s

usr/local/scenix/samples/common/src/SceniXWidget.o: usr/local/scenix/samples/common/src/SceniXWidget.cpp.o
.PHONY : usr/local/scenix/samples/common/src/SceniXWidget.o

# target to build an object file
usr/local/scenix/samples/common/src/SceniXWidget.cpp.o:
	$(MAKE) -f CMakeFiles/SDLNV.dir/build.make CMakeFiles/SDLNV.dir/usr/local/scenix/samples/common/src/SceniXWidget.cpp.o
.PHONY : usr/local/scenix/samples/common/src/SceniXWidget.cpp.o

usr/local/scenix/samples/common/src/SceniXWidget.i: usr/local/scenix/samples/common/src/SceniXWidget.cpp.i
.PHONY : usr/local/scenix/samples/common/src/SceniXWidget.i

# target to preprocess a source file
usr/local/scenix/samples/common/src/SceniXWidget.cpp.i:
	$(MAKE) -f CMakeFiles/SDLNV.dir/build.make CMakeFiles/SDLNV.dir/usr/local/scenix/samples/common/src/SceniXWidget.cpp.i
.PHONY : usr/local/scenix/samples/common/src/SceniXWidget.cpp.i

usr/local/scenix/samples/common/src/SceniXWidget.s: usr/local/scenix/samples/common/src/SceniXWidget.cpp.s
.PHONY : usr/local/scenix/samples/common/src/SceniXWidget.s

# target to generate assembly for a file
usr/local/scenix/samples/common/src/SceniXWidget.cpp.s:
	$(MAKE) -f CMakeFiles/SDLNV.dir/build.make CMakeFiles/SDLNV.dir/usr/local/scenix/samples/common/src/SceniXWidget.cpp.s
.PHONY : usr/local/scenix/samples/common/src/SceniXWidget.cpp.s

usr/local/scenix/samples/common/src/ui/AnimationManipulator.o: usr/local/scenix/samples/common/src/ui/AnimationManipulator.cpp.o
.PHONY : usr/local/scenix/samples/common/src/ui/AnimationManipulator.o

# target to build an object file
usr/local/scenix/samples/common/src/ui/AnimationManipulator.cpp.o:
	$(MAKE) -f CMakeFiles/SDLNV.dir/build.make CMakeFiles/SDLNV.dir/usr/local/scenix/samples/common/src/ui/AnimationManipulator.cpp.o
.PHONY : usr/local/scenix/samples/common/src/ui/AnimationManipulator.cpp.o

usr/local/scenix/samples/common/src/ui/AnimationManipulator.i: usr/local/scenix/samples/common/src/ui/AnimationManipulator.cpp.i
.PHONY : usr/local/scenix/samples/common/src/ui/AnimationManipulator.i

# target to preprocess a source file
usr/local/scenix/samples/common/src/ui/AnimationManipulator.cpp.i:
	$(MAKE) -f CMakeFiles/SDLNV.dir/build.make CMakeFiles/SDLNV.dir/usr/local/scenix/samples/common/src/ui/AnimationManipulator.cpp.i
.PHONY : usr/local/scenix/samples/common/src/ui/AnimationManipulator.cpp.i

usr/local/scenix/samples/common/src/ui/AnimationManipulator.s: usr/local/scenix/samples/common/src/ui/AnimationManipulator.cpp.s
.PHONY : usr/local/scenix/samples/common/src/ui/AnimationManipulator.s

# target to generate assembly for a file
usr/local/scenix/samples/common/src/ui/AnimationManipulator.cpp.s:
	$(MAKE) -f CMakeFiles/SDLNV.dir/build.make CMakeFiles/SDLNV.dir/usr/local/scenix/samples/common/src/ui/AnimationManipulator.cpp.s
.PHONY : usr/local/scenix/samples/common/src/ui/AnimationManipulator.cpp.s

usr/local/scenix/samples/common/src/ui/CylindricalCameraManipulator.o: usr/local/scenix/samples/common/src/ui/CylindricalCameraManipulator.cpp.o
.PHONY : usr/local/scenix/samples/common/src/ui/CylindricalCameraManipulator.o

# target to build an object file
usr/local/scenix/samples/common/src/ui/CylindricalCameraManipulator.cpp.o:
	$(MAKE) -f CMakeFiles/SDLNV.dir/build.make CMakeFiles/SDLNV.dir/usr/local/scenix/samples/common/src/ui/CylindricalCameraManipulator.cpp.o
.PHONY : usr/local/scenix/samples/common/src/ui/CylindricalCameraManipulator.cpp.o

usr/local/scenix/samples/common/src/ui/CylindricalCameraManipulator.i: usr/local/scenix/samples/common/src/ui/CylindricalCameraManipulator.cpp.i
.PHONY : usr/local/scenix/samples/common/src/ui/CylindricalCameraManipulator.i

# target to preprocess a source file
usr/local/scenix/samples/common/src/ui/CylindricalCameraManipulator.cpp.i:
	$(MAKE) -f CMakeFiles/SDLNV.dir/build.make CMakeFiles/SDLNV.dir/usr/local/scenix/samples/common/src/ui/CylindricalCameraManipulator.cpp.i
.PHONY : usr/local/scenix/samples/common/src/ui/CylindricalCameraManipulator.cpp.i

usr/local/scenix/samples/common/src/ui/CylindricalCameraManipulator.s: usr/local/scenix/samples/common/src/ui/CylindricalCameraManipulator.cpp.s
.PHONY : usr/local/scenix/samples/common/src/ui/CylindricalCameraManipulator.s

# target to generate assembly for a file
usr/local/scenix/samples/common/src/ui/CylindricalCameraManipulator.cpp.s:
	$(MAKE) -f CMakeFiles/SDLNV.dir/build.make CMakeFiles/SDLNV.dir/usr/local/scenix/samples/common/src/ui/CylindricalCameraManipulator.cpp.s
.PHONY : usr/local/scenix/samples/common/src/ui/CylindricalCameraManipulator.cpp.s

usr/local/scenix/samples/common/src/ui/CylindricalCameraManipulatorHIDSync.o: usr/local/scenix/samples/common/src/ui/CylindricalCameraManipulatorHIDSync.cpp.o
.PHONY : usr/local/scenix/samples/common/src/ui/CylindricalCameraManipulatorHIDSync.o

# target to build an object file
usr/local/scenix/samples/common/src/ui/CylindricalCameraManipulatorHIDSync.cpp.o:
	$(MAKE) -f CMakeFiles/SDLNV.dir/build.make CMakeFiles/SDLNV.dir/usr/local/scenix/samples/common/src/ui/CylindricalCameraManipulatorHIDSync.cpp.o
.PHONY : usr/local/scenix/samples/common/src/ui/CylindricalCameraManipulatorHIDSync.cpp.o

usr/local/scenix/samples/common/src/ui/CylindricalCameraManipulatorHIDSync.i: usr/local/scenix/samples/common/src/ui/CylindricalCameraManipulatorHIDSync.cpp.i
.PHONY : usr/local/scenix/samples/common/src/ui/CylindricalCameraManipulatorHIDSync.i

# target to preprocess a source file
usr/local/scenix/samples/common/src/ui/CylindricalCameraManipulatorHIDSync.cpp.i:
	$(MAKE) -f CMakeFiles/SDLNV.dir/build.make CMakeFiles/SDLNV.dir/usr/local/scenix/samples/common/src/ui/CylindricalCameraManipulatorHIDSync.cpp.i
.PHONY : usr/local/scenix/samples/common/src/ui/CylindricalCameraManipulatorHIDSync.cpp.i

usr/local/scenix/samples/common/src/ui/CylindricalCameraManipulatorHIDSync.s: usr/local/scenix/samples/common/src/ui/CylindricalCameraManipulatorHIDSync.cpp.s
.PHONY : usr/local/scenix/samples/common/src/ui/CylindricalCameraManipulatorHIDSync.s

# target to generate assembly for a file
usr/local/scenix/samples/common/src/ui/CylindricalCameraManipulatorHIDSync.cpp.s:
	$(MAKE) -f CMakeFiles/SDLNV.dir/build.make CMakeFiles/SDLNV.dir/usr/local/scenix/samples/common/src/ui/CylindricalCameraManipulatorHIDSync.cpp.s
.PHONY : usr/local/scenix/samples/common/src/ui/CylindricalCameraManipulatorHIDSync.cpp.s

usr/local/scenix/samples/common/src/ui/FlightCameraManipulator.o: usr/local/scenix/samples/common/src/ui/FlightCameraManipulator.cpp.o
.PHONY : usr/local/scenix/samples/common/src/ui/FlightCameraManipulator.o

# target to build an object file
usr/local/scenix/samples/common/src/ui/FlightCameraManipulator.cpp.o:
	$(MAKE) -f CMakeFiles/SDLNV.dir/build.make CMakeFiles/SDLNV.dir/usr/local/scenix/samples/common/src/ui/FlightCameraManipulator.cpp.o
.PHONY : usr/local/scenix/samples/common/src/ui/FlightCameraManipulator.cpp.o

usr/local/scenix/samples/common/src/ui/FlightCameraManipulator.i: usr/local/scenix/samples/common/src/ui/FlightCameraManipulator.cpp.i
.PHONY : usr/local/scenix/samples/common/src/ui/FlightCameraManipulator.i

# target to preprocess a source file
usr/local/scenix/samples/common/src/ui/FlightCameraManipulator.cpp.i:
	$(MAKE) -f CMakeFiles/SDLNV.dir/build.make CMakeFiles/SDLNV.dir/usr/local/scenix/samples/common/src/ui/FlightCameraManipulator.cpp.i
.PHONY : usr/local/scenix/samples/common/src/ui/FlightCameraManipulator.cpp.i

usr/local/scenix/samples/common/src/ui/FlightCameraManipulator.s: usr/local/scenix/samples/common/src/ui/FlightCameraManipulator.cpp.s
.PHONY : usr/local/scenix/samples/common/src/ui/FlightCameraManipulator.s

# target to generate assembly for a file
usr/local/scenix/samples/common/src/ui/FlightCameraManipulator.cpp.s:
	$(MAKE) -f CMakeFiles/SDLNV.dir/build.make CMakeFiles/SDLNV.dir/usr/local/scenix/samples/common/src/ui/FlightCameraManipulator.cpp.s
.PHONY : usr/local/scenix/samples/common/src/ui/FlightCameraManipulator.cpp.s

usr/local/scenix/samples/common/src/ui/FlightCameraManipulatorHIDSync.o: usr/local/scenix/samples/common/src/ui/FlightCameraManipulatorHIDSync.cpp.o
.PHONY : usr/local/scenix/samples/common/src/ui/FlightCameraManipulatorHIDSync.o

# target to build an object file
usr/local/scenix/samples/common/src/ui/FlightCameraManipulatorHIDSync.cpp.o:
	$(MAKE) -f CMakeFiles/SDLNV.dir/build.make CMakeFiles/SDLNV.dir/usr/local/scenix/samples/common/src/ui/FlightCameraManipulatorHIDSync.cpp.o
.PHONY : usr/local/scenix/samples/common/src/ui/FlightCameraManipulatorHIDSync.cpp.o

usr/local/scenix/samples/common/src/ui/FlightCameraManipulatorHIDSync.i: usr/local/scenix/samples/common/src/ui/FlightCameraManipulatorHIDSync.cpp.i
.PHONY : usr/local/scenix/samples/common/src/ui/FlightCameraManipulatorHIDSync.i

# target to preprocess a source file
usr/local/scenix/samples/common/src/ui/FlightCameraManipulatorHIDSync.cpp.i:
	$(MAKE) -f CMakeFiles/SDLNV.dir/build.make CMakeFiles/SDLNV.dir/usr/local/scenix/samples/common/src/ui/FlightCameraManipulatorHIDSync.cpp.i
.PHONY : usr/local/scenix/samples/common/src/ui/FlightCameraManipulatorHIDSync.cpp.i

usr/local/scenix/samples/common/src/ui/FlightCameraManipulatorHIDSync.s: usr/local/scenix/samples/common/src/ui/FlightCameraManipulatorHIDSync.cpp.s
.PHONY : usr/local/scenix/samples/common/src/ui/FlightCameraManipulatorHIDSync.s

# target to generate assembly for a file
usr/local/scenix/samples/common/src/ui/FlightCameraManipulatorHIDSync.cpp.s:
	$(MAKE) -f CMakeFiles/SDLNV.dir/build.make CMakeFiles/SDLNV.dir/usr/local/scenix/samples/common/src/ui/FlightCameraManipulatorHIDSync.cpp.s
.PHONY : usr/local/scenix/samples/common/src/ui/FlightCameraManipulatorHIDSync.cpp.s

usr/local/scenix/samples/common/src/ui/HumanInterfaceDevice.o: usr/local/scenix/samples/common/src/ui/HumanInterfaceDevice.cpp.o
.PHONY : usr/local/scenix/samples/common/src/ui/HumanInterfaceDevice.o

# target to build an object file
usr/local/scenix/samples/common/src/ui/HumanInterfaceDevice.cpp.o:
	$(MAKE) -f CMakeFiles/SDLNV.dir/build.make CMakeFiles/SDLNV.dir/usr/local/scenix/samples/common/src/ui/HumanInterfaceDevice.cpp.o
.PHONY : usr/local/scenix/samples/common/src/ui/HumanInterfaceDevice.cpp.o

usr/local/scenix/samples/common/src/ui/HumanInterfaceDevice.i: usr/local/scenix/samples/common/src/ui/HumanInterfaceDevice.cpp.i
.PHONY : usr/local/scenix/samples/common/src/ui/HumanInterfaceDevice.i

# target to preprocess a source file
usr/local/scenix/samples/common/src/ui/HumanInterfaceDevice.cpp.i:
	$(MAKE) -f CMakeFiles/SDLNV.dir/build.make CMakeFiles/SDLNV.dir/usr/local/scenix/samples/common/src/ui/HumanInterfaceDevice.cpp.i
.PHONY : usr/local/scenix/samples/common/src/ui/HumanInterfaceDevice.cpp.i

usr/local/scenix/samples/common/src/ui/HumanInterfaceDevice.s: usr/local/scenix/samples/common/src/ui/HumanInterfaceDevice.cpp.s
.PHONY : usr/local/scenix/samples/common/src/ui/HumanInterfaceDevice.s

# target to generate assembly for a file
usr/local/scenix/samples/common/src/ui/HumanInterfaceDevice.cpp.s:
	$(MAKE) -f CMakeFiles/SDLNV.dir/build.make CMakeFiles/SDLNV.dir/usr/local/scenix/samples/common/src/ui/HumanInterfaceDevice.cpp.s
.PHONY : usr/local/scenix/samples/common/src/ui/HumanInterfaceDevice.cpp.s

usr/local/scenix/samples/common/src/ui/Manipulator.o: usr/local/scenix/samples/common/src/ui/Manipulator.cpp.o
.PHONY : usr/local/scenix/samples/common/src/ui/Manipulator.o

# target to build an object file
usr/local/scenix/samples/common/src/ui/Manipulator.cpp.o:
	$(MAKE) -f CMakeFiles/SDLNV.dir/build.make CMakeFiles/SDLNV.dir/usr/local/scenix/samples/common/src/ui/Manipulator.cpp.o
.PHONY : usr/local/scenix/samples/common/src/ui/Manipulator.cpp.o

usr/local/scenix/samples/common/src/ui/Manipulator.i: usr/local/scenix/samples/common/src/ui/Manipulator.cpp.i
.PHONY : usr/local/scenix/samples/common/src/ui/Manipulator.i

# target to preprocess a source file
usr/local/scenix/samples/common/src/ui/Manipulator.cpp.i:
	$(MAKE) -f CMakeFiles/SDLNV.dir/build.make CMakeFiles/SDLNV.dir/usr/local/scenix/samples/common/src/ui/Manipulator.cpp.i
.PHONY : usr/local/scenix/samples/common/src/ui/Manipulator.cpp.i

usr/local/scenix/samples/common/src/ui/Manipulator.s: usr/local/scenix/samples/common/src/ui/Manipulator.cpp.s
.PHONY : usr/local/scenix/samples/common/src/ui/Manipulator.s

# target to generate assembly for a file
usr/local/scenix/samples/common/src/ui/Manipulator.cpp.s:
	$(MAKE) -f CMakeFiles/SDLNV.dir/build.make CMakeFiles/SDLNV.dir/usr/local/scenix/samples/common/src/ui/Manipulator.cpp.s
.PHONY : usr/local/scenix/samples/common/src/ui/Manipulator.cpp.s

usr/local/scenix/samples/common/src/ui/TrackballCameraManipulator.o: usr/local/scenix/samples/common/src/ui/TrackballCameraManipulator.cpp.o
.PHONY : usr/local/scenix/samples/common/src/ui/TrackballCameraManipulator.o

# target to build an object file
usr/local/scenix/samples/common/src/ui/TrackballCameraManipulator.cpp.o:
	$(MAKE) -f CMakeFiles/SDLNV.dir/build.make CMakeFiles/SDLNV.dir/usr/local/scenix/samples/common/src/ui/TrackballCameraManipulator.cpp.o
.PHONY : usr/local/scenix/samples/common/src/ui/TrackballCameraManipulator.cpp.o

usr/local/scenix/samples/common/src/ui/TrackballCameraManipulator.i: usr/local/scenix/samples/common/src/ui/TrackballCameraManipulator.cpp.i
.PHONY : usr/local/scenix/samples/common/src/ui/TrackballCameraManipulator.i

# target to preprocess a source file
usr/local/scenix/samples/common/src/ui/TrackballCameraManipulator.cpp.i:
	$(MAKE) -f CMakeFiles/SDLNV.dir/build.make CMakeFiles/SDLNV.dir/usr/local/scenix/samples/common/src/ui/TrackballCameraManipulator.cpp.i
.PHONY : usr/local/scenix/samples/common/src/ui/TrackballCameraManipulator.cpp.i

usr/local/scenix/samples/common/src/ui/TrackballCameraManipulator.s: usr/local/scenix/samples/common/src/ui/TrackballCameraManipulator.cpp.s
.PHONY : usr/local/scenix/samples/common/src/ui/TrackballCameraManipulator.s

# target to generate assembly for a file
usr/local/scenix/samples/common/src/ui/TrackballCameraManipulator.cpp.s:
	$(MAKE) -f CMakeFiles/SDLNV.dir/build.make CMakeFiles/SDLNV.dir/usr/local/scenix/samples/common/src/ui/TrackballCameraManipulator.cpp.s
.PHONY : usr/local/scenix/samples/common/src/ui/TrackballCameraManipulator.cpp.s

usr/local/scenix/samples/common/src/ui/TrackballCameraManipulatorHIDSync.o: usr/local/scenix/samples/common/src/ui/TrackballCameraManipulatorHIDSync.cpp.o
.PHONY : usr/local/scenix/samples/common/src/ui/TrackballCameraManipulatorHIDSync.o

# target to build an object file
usr/local/scenix/samples/common/src/ui/TrackballCameraManipulatorHIDSync.cpp.o:
	$(MAKE) -f CMakeFiles/SDLNV.dir/build.make CMakeFiles/SDLNV.dir/usr/local/scenix/samples/common/src/ui/TrackballCameraManipulatorHIDSync.cpp.o
.PHONY : usr/local/scenix/samples/common/src/ui/TrackballCameraManipulatorHIDSync.cpp.o

usr/local/scenix/samples/common/src/ui/TrackballCameraManipulatorHIDSync.i: usr/local/scenix/samples/common/src/ui/TrackballCameraManipulatorHIDSync.cpp.i
.PHONY : usr/local/scenix/samples/common/src/ui/TrackballCameraManipulatorHIDSync.i

# target to preprocess a source file
usr/local/scenix/samples/common/src/ui/TrackballCameraManipulatorHIDSync.cpp.i:
	$(MAKE) -f CMakeFiles/SDLNV.dir/build.make CMakeFiles/SDLNV.dir/usr/local/scenix/samples/common/src/ui/TrackballCameraManipulatorHIDSync.cpp.i
.PHONY : usr/local/scenix/samples/common/src/ui/TrackballCameraManipulatorHIDSync.cpp.i

usr/local/scenix/samples/common/src/ui/TrackballCameraManipulatorHIDSync.s: usr/local/scenix/samples/common/src/ui/TrackballCameraManipulatorHIDSync.cpp.s
.PHONY : usr/local/scenix/samples/common/src/ui/TrackballCameraManipulatorHIDSync.s

# target to generate assembly for a file
usr/local/scenix/samples/common/src/ui/TrackballCameraManipulatorHIDSync.cpp.s:
	$(MAKE) -f CMakeFiles/SDLNV.dir/build.make CMakeFiles/SDLNV.dir/usr/local/scenix/samples/common/src/ui/TrackballCameraManipulatorHIDSync.cpp.s
.PHONY : usr/local/scenix/samples/common/src/ui/TrackballCameraManipulatorHIDSync.cpp.s

usr/local/scenix/samples/common/src/ui/TrackballTransformManipulator.o: usr/local/scenix/samples/common/src/ui/TrackballTransformManipulator.cpp.o
.PHONY : usr/local/scenix/samples/common/src/ui/TrackballTransformManipulator.o

# target to build an object file
usr/local/scenix/samples/common/src/ui/TrackballTransformManipulator.cpp.o:
	$(MAKE) -f CMakeFiles/SDLNV.dir/build.make CMakeFiles/SDLNV.dir/usr/local/scenix/samples/common/src/ui/TrackballTransformManipulator.cpp.o
.PHONY : usr/local/scenix/samples/common/src/ui/TrackballTransformManipulator.cpp.o

usr/local/scenix/samples/common/src/ui/TrackballTransformManipulator.i: usr/local/scenix/samples/common/src/ui/TrackballTransformManipulator.cpp.i
.PHONY : usr/local/scenix/samples/common/src/ui/TrackballTransformManipulator.i

# target to preprocess a source file
usr/local/scenix/samples/common/src/ui/TrackballTransformManipulator.cpp.i:
	$(MAKE) -f CMakeFiles/SDLNV.dir/build.make CMakeFiles/SDLNV.dir/usr/local/scenix/samples/common/src/ui/TrackballTransformManipulator.cpp.i
.PHONY : usr/local/scenix/samples/common/src/ui/TrackballTransformManipulator.cpp.i

usr/local/scenix/samples/common/src/ui/TrackballTransformManipulator.s: usr/local/scenix/samples/common/src/ui/TrackballTransformManipulator.cpp.s
.PHONY : usr/local/scenix/samples/common/src/ui/TrackballTransformManipulator.s

# target to generate assembly for a file
usr/local/scenix/samples/common/src/ui/TrackballTransformManipulator.cpp.s:
	$(MAKE) -f CMakeFiles/SDLNV.dir/build.make CMakeFiles/SDLNV.dir/usr/local/scenix/samples/common/src/ui/TrackballTransformManipulator.cpp.s
.PHONY : usr/local/scenix/samples/common/src/ui/TrackballTransformManipulator.cpp.s

usr/local/scenix/samples/common/src/ui/TrackballTransformManipulatorHIDSync.o: usr/local/scenix/samples/common/src/ui/TrackballTransformManipulatorHIDSync.cpp.o
.PHONY : usr/local/scenix/samples/common/src/ui/TrackballTransformManipulatorHIDSync.o

# target to build an object file
usr/local/scenix/samples/common/src/ui/TrackballTransformManipulatorHIDSync.cpp.o:
	$(MAKE) -f CMakeFiles/SDLNV.dir/build.make CMakeFiles/SDLNV.dir/usr/local/scenix/samples/common/src/ui/TrackballTransformManipulatorHIDSync.cpp.o
.PHONY : usr/local/scenix/samples/common/src/ui/TrackballTransformManipulatorHIDSync.cpp.o

usr/local/scenix/samples/common/src/ui/TrackballTransformManipulatorHIDSync.i: usr/local/scenix/samples/common/src/ui/TrackballTransformManipulatorHIDSync.cpp.i
.PHONY : usr/local/scenix/samples/common/src/ui/TrackballTransformManipulatorHIDSync.i

# target to preprocess a source file
usr/local/scenix/samples/common/src/ui/TrackballTransformManipulatorHIDSync.cpp.i:
	$(MAKE) -f CMakeFiles/SDLNV.dir/build.make CMakeFiles/SDLNV.dir/usr/local/scenix/samples/common/src/ui/TrackballTransformManipulatorHIDSync.cpp.i
.PHONY : usr/local/scenix/samples/common/src/ui/TrackballTransformManipulatorHIDSync.cpp.i

usr/local/scenix/samples/common/src/ui/TrackballTransformManipulatorHIDSync.s: usr/local/scenix/samples/common/src/ui/TrackballTransformManipulatorHIDSync.cpp.s
.PHONY : usr/local/scenix/samples/common/src/ui/TrackballTransformManipulatorHIDSync.s

# target to generate assembly for a file
usr/local/scenix/samples/common/src/ui/TrackballTransformManipulatorHIDSync.cpp.s:
	$(MAKE) -f CMakeFiles/SDLNV.dir/build.make CMakeFiles/SDLNV.dir/usr/local/scenix/samples/common/src/ui/TrackballTransformManipulatorHIDSync.cpp.s
.PHONY : usr/local/scenix/samples/common/src/ui/TrackballTransformManipulatorHIDSync.cpp.s

usr/local/scenix/samples/common/src/ui/WalkCameraManipulator.o: usr/local/scenix/samples/common/src/ui/WalkCameraManipulator.cpp.o
.PHONY : usr/local/scenix/samples/common/src/ui/WalkCameraManipulator.o

# target to build an object file
usr/local/scenix/samples/common/src/ui/WalkCameraManipulator.cpp.o:
	$(MAKE) -f CMakeFiles/SDLNV.dir/build.make CMakeFiles/SDLNV.dir/usr/local/scenix/samples/common/src/ui/WalkCameraManipulator.cpp.o
.PHONY : usr/local/scenix/samples/common/src/ui/WalkCameraManipulator.cpp.o

usr/local/scenix/samples/common/src/ui/WalkCameraManipulator.i: usr/local/scenix/samples/common/src/ui/WalkCameraManipulator.cpp.i
.PHONY : usr/local/scenix/samples/common/src/ui/WalkCameraManipulator.i

# target to preprocess a source file
usr/local/scenix/samples/common/src/ui/WalkCameraManipulator.cpp.i:
	$(MAKE) -f CMakeFiles/SDLNV.dir/build.make CMakeFiles/SDLNV.dir/usr/local/scenix/samples/common/src/ui/WalkCameraManipulator.cpp.i
.PHONY : usr/local/scenix/samples/common/src/ui/WalkCameraManipulator.cpp.i

usr/local/scenix/samples/common/src/ui/WalkCameraManipulator.s: usr/local/scenix/samples/common/src/ui/WalkCameraManipulator.cpp.s
.PHONY : usr/local/scenix/samples/common/src/ui/WalkCameraManipulator.s

# target to generate assembly for a file
usr/local/scenix/samples/common/src/ui/WalkCameraManipulator.cpp.s:
	$(MAKE) -f CMakeFiles/SDLNV.dir/build.make CMakeFiles/SDLNV.dir/usr/local/scenix/samples/common/src/ui/WalkCameraManipulator.cpp.s
.PHONY : usr/local/scenix/samples/common/src/ui/WalkCameraManipulator.cpp.s

usr/local/scenix/samples/common/src/ui/WalkCameraManipulatorHIDSync.o: usr/local/scenix/samples/common/src/ui/WalkCameraManipulatorHIDSync.cpp.o
.PHONY : usr/local/scenix/samples/common/src/ui/WalkCameraManipulatorHIDSync.o

# target to build an object file
usr/local/scenix/samples/common/src/ui/WalkCameraManipulatorHIDSync.cpp.o:
	$(MAKE) -f CMakeFiles/SDLNV.dir/build.make CMakeFiles/SDLNV.dir/usr/local/scenix/samples/common/src/ui/WalkCameraManipulatorHIDSync.cpp.o
.PHONY : usr/local/scenix/samples/common/src/ui/WalkCameraManipulatorHIDSync.cpp.o

usr/local/scenix/samples/common/src/ui/WalkCameraManipulatorHIDSync.i: usr/local/scenix/samples/common/src/ui/WalkCameraManipulatorHIDSync.cpp.i
.PHONY : usr/local/scenix/samples/common/src/ui/WalkCameraManipulatorHIDSync.i

# target to preprocess a source file
usr/local/scenix/samples/common/src/ui/WalkCameraManipulatorHIDSync.cpp.i:
	$(MAKE) -f CMakeFiles/SDLNV.dir/build.make CMakeFiles/SDLNV.dir/usr/local/scenix/samples/common/src/ui/WalkCameraManipulatorHIDSync.cpp.i
.PHONY : usr/local/scenix/samples/common/src/ui/WalkCameraManipulatorHIDSync.cpp.i

usr/local/scenix/samples/common/src/ui/WalkCameraManipulatorHIDSync.s: usr/local/scenix/samples/common/src/ui/WalkCameraManipulatorHIDSync.cpp.s
.PHONY : usr/local/scenix/samples/common/src/ui/WalkCameraManipulatorHIDSync.s

# target to generate assembly for a file
usr/local/scenix/samples/common/src/ui/WalkCameraManipulatorHIDSync.cpp.s:
	$(MAKE) -f CMakeFiles/SDLNV.dir/build.make CMakeFiles/SDLNV.dir/usr/local/scenix/samples/common/src/ui/WalkCameraManipulatorHIDSync.cpp.s
.PHONY : usr/local/scenix/samples/common/src/ui/WalkCameraManipulatorHIDSync.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... SDLNV"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... src/Agent.o"
	@echo "... src/Agent.i"
	@echo "... src/Agent.s"
	@echo "... src/AgentDynamic.o"
	@echo "... src/AgentDynamic.i"
	@echo "... src/AgentDynamic.s"
	@echo "... src/CameraSystem.o"
	@echo "... src/CameraSystem.i"
	@echo "... src/CameraSystem.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... usr/local/scenix/samples/common/src/AIScene.o"
	@echo "... usr/local/scenix/samples/common/src/AIScene.i"
	@echo "... usr/local/scenix/samples/common/src/AIScene.s"
	@echo "... usr/local/scenix/samples/common/src/MeshGenerator.o"
	@echo "... usr/local/scenix/samples/common/src/MeshGenerator.i"
	@echo "... usr/local/scenix/samples/common/src/MeshGenerator.s"
	@echo "... usr/local/scenix/samples/common/src/SceneFunctions.o"
	@echo "... usr/local/scenix/samples/common/src/SceneFunctions.i"
	@echo "... usr/local/scenix/samples/common/src/SceneFunctions.s"
	@echo "... usr/local/scenix/samples/common/src/SceniXWidget.o"
	@echo "... usr/local/scenix/samples/common/src/SceniXWidget.i"
	@echo "... usr/local/scenix/samples/common/src/SceniXWidget.s"
	@echo "... usr/local/scenix/samples/common/src/ui/AnimationManipulator.o"
	@echo "... usr/local/scenix/samples/common/src/ui/AnimationManipulator.i"
	@echo "... usr/local/scenix/samples/common/src/ui/AnimationManipulator.s"
	@echo "... usr/local/scenix/samples/common/src/ui/CylindricalCameraManipulator.o"
	@echo "... usr/local/scenix/samples/common/src/ui/CylindricalCameraManipulator.i"
	@echo "... usr/local/scenix/samples/common/src/ui/CylindricalCameraManipulator.s"
	@echo "... usr/local/scenix/samples/common/src/ui/CylindricalCameraManipulatorHIDSync.o"
	@echo "... usr/local/scenix/samples/common/src/ui/CylindricalCameraManipulatorHIDSync.i"
	@echo "... usr/local/scenix/samples/common/src/ui/CylindricalCameraManipulatorHIDSync.s"
	@echo "... usr/local/scenix/samples/common/src/ui/FlightCameraManipulator.o"
	@echo "... usr/local/scenix/samples/common/src/ui/FlightCameraManipulator.i"
	@echo "... usr/local/scenix/samples/common/src/ui/FlightCameraManipulator.s"
	@echo "... usr/local/scenix/samples/common/src/ui/FlightCameraManipulatorHIDSync.o"
	@echo "... usr/local/scenix/samples/common/src/ui/FlightCameraManipulatorHIDSync.i"
	@echo "... usr/local/scenix/samples/common/src/ui/FlightCameraManipulatorHIDSync.s"
	@echo "... usr/local/scenix/samples/common/src/ui/HumanInterfaceDevice.o"
	@echo "... usr/local/scenix/samples/common/src/ui/HumanInterfaceDevice.i"
	@echo "... usr/local/scenix/samples/common/src/ui/HumanInterfaceDevice.s"
	@echo "... usr/local/scenix/samples/common/src/ui/Manipulator.o"
	@echo "... usr/local/scenix/samples/common/src/ui/Manipulator.i"
	@echo "... usr/local/scenix/samples/common/src/ui/Manipulator.s"
	@echo "... usr/local/scenix/samples/common/src/ui/TrackballCameraManipulator.o"
	@echo "... usr/local/scenix/samples/common/src/ui/TrackballCameraManipulator.i"
	@echo "... usr/local/scenix/samples/common/src/ui/TrackballCameraManipulator.s"
	@echo "... usr/local/scenix/samples/common/src/ui/TrackballCameraManipulatorHIDSync.o"
	@echo "... usr/local/scenix/samples/common/src/ui/TrackballCameraManipulatorHIDSync.i"
	@echo "... usr/local/scenix/samples/common/src/ui/TrackballCameraManipulatorHIDSync.s"
	@echo "... usr/local/scenix/samples/common/src/ui/TrackballTransformManipulator.o"
	@echo "... usr/local/scenix/samples/common/src/ui/TrackballTransformManipulator.i"
	@echo "... usr/local/scenix/samples/common/src/ui/TrackballTransformManipulator.s"
	@echo "... usr/local/scenix/samples/common/src/ui/TrackballTransformManipulatorHIDSync.o"
	@echo "... usr/local/scenix/samples/common/src/ui/TrackballTransformManipulatorHIDSync.i"
	@echo "... usr/local/scenix/samples/common/src/ui/TrackballTransformManipulatorHIDSync.s"
	@echo "... usr/local/scenix/samples/common/src/ui/WalkCameraManipulator.o"
	@echo "... usr/local/scenix/samples/common/src/ui/WalkCameraManipulator.i"
	@echo "... usr/local/scenix/samples/common/src/ui/WalkCameraManipulator.s"
	@echo "... usr/local/scenix/samples/common/src/ui/WalkCameraManipulatorHIDSync.o"
	@echo "... usr/local/scenix/samples/common/src/ui/WalkCameraManipulatorHIDSync.i"
	@echo "... usr/local/scenix/samples/common/src/ui/WalkCameraManipulatorHIDSync.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

